cd ../data/ && { python3 get_gt.py 2020-06-22 ../data/temperature/ ../data/precipitation/ ; cd -; }
cd ../data/ && { python3 get_gt.py 2020-06-09 ../data/temperature/ ../data/precipitation/ ; cd -; }
cd ../data/ && { python3 get_gt.py 2020-05-26 ../data/temperature/ ../data/precipitation/ ; cd -; }
cd ../data/ && { python3 get_gt.py 2020-05-12 ../data/temperature/ ../data/precipitation/ ; cd -; }
cd ../data/ && { python3 get_gt.py 2020-04-28 ../data/temperature/ ../data/precipitation/ ; cd -; }
cd ../data/ && { python3 get_gt.py 2020-04-14 ../data/temperature/ ../data/precipitation/ ; cd -; }
cd ../data/ && { python3 get_gt.py 2020-03-31 ../data/temperature/ ../data/precipitation/ ; cd -; }
cd ../data/ && { python3 get_gt.py 2020-03-17 ../data/temperature/ ../data/precipitation/ ; cd -; }
cd ../data/ && { python3 get_gt.py 2020-03-03 ../data/temperature/ ../data/precipitation/ ; cd -; }
cd ../data/ && { python3 get_gt.py 2020-02-18 ../data/temperature/ ../data/precipitation/ ; cd -; }
cd ../data/ && { python3 get_gt.py 2020-02-04 ../data/temperature/ ../data/precipitation/ ; cd -; }
cd ../data/ && { python3 get_gt.py 2020-01-21 ../data/temperature/ ../data/precipitation/ ; cd -; }
cd ../data/ && { python3 get_gt.py 2020-01-07 ../data/temperature/ ../data/precipitation/ ; cd -; }
cd ../data/ && { python3 get_gt.py 2019-12-24 ../data/temperature/ ../data/precipitation/ ; cd -; }
cd ../data/ && { python3 get_gt.py 2019-12-10 ../data/temperature/ ../data/precipitation/ ; cd -; }
cd ../data/ && { python3 get_gt.py 2019-11-26 ../data/temperature/ ../data/precipitation/ ; cd -; }
cd ../data/ && { python3 get_gt.py 2019-11-12 ../data/temperature/ ../data/precipitation/ ; cd -; }
cd ../data/ && { python3 get_gt.py 2019-10-29 ../data/temperature/ ../data/precipitation/ ; cd -; }
cd ../data/ && { python3 get_gt.py 2019-10-15 ../data/temperature/ ../data/precipitation/ ; cd -; }
cd ../data/ && { python3 get_gt.py 2019-10-01 ../data/temperature/ ../data/precipitation/ ; cd -; }
cd ../data/ && { python3 get_gt.py 2019-09-17 ../data/temperature/ ../data/precipitation/ ; cd -; }
cd ../data/ && { python3 get_gt.py 2019-09-03 ../data/temperature/ ../data/precipitation/ ; cd -; }
cd ../data/ && { python3 get_gt.py 2019-08-20 ../data/temperature/ ../data/precipitation/ ; cd -; }
cd ../data/ && { python3 get_gt.py 2019-08-06 ../data/temperature/ ../data/precipitation/ ; cd -; }
cd ../data/ && { python3 get_gt.py 2019-07-23 ../data/temperature/ ../data/precipitation/ ; cd -; }
cd ../data/ && { python3 get_gt.py 2019-07-09 ../data/temperature/ ../data/precipitation/ ; cd -; }